# name: four-jobs
# on: push

# jobs:
#     job1:
#         name: first-job
#         runs-on: ubuntu-latest
#         steps:
#         - name: step-1
#           run: date
#     job2:
#         name: second-job
#         runs-on: windows-latest
#         steps:
#         - name: step-1
#           run: date
#     job3:
#         name: third-job
#         runs-on: macos-latest
#         steps:
#         - name: step-1
#           run: date
#     job4:
#         name: fourth-job
#         runs-on: macos-latest
#         steps:
#         - name: step-1
#           run: date