name: validating json file
on: 
  pull_request:
    branches:
      - main
    paths:
      - 'input.json'
jobs:
  validate-json:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: executing shell script
        run: |
          echo "Validating PR title and branch name"
          branch="${{ github.event.pull_request.head.ref }}"
          title="${{ github.event.pull_request.title }}"
          echo "Branch name is ${branch}"
          echo "PR title is ${{title}}"
          if [[ $branch =~ ^SRE|^ZD ]];
          then
            if [[ $title =~ ^\[SRE|^\[ZD  ]];
            then
              echo "PR title and branch name are valid"
              exit 0
            else
              echo "The PR title should start with SRE or ZD ticket number. For example:- [SRE-1234] Adding new user"
            exit 1
            fi
          else
            echo "Invalid branch name. The branch name should start with ZD or SRE ticket number. For example:- SRE-1234-add-user"
            exit 1
          fi
      - name: Validate JSON
        uses: docker://orrosenblatt/validate-json-action:latest
        env:
          INPUT_SCHEMA: /schema.json
          INPUT_JSONS: /input.json

