name: validating json file
on: 
  pull_request:
    branches:
      - main
    paths:
      - 'input.json'
jobs:
  validate-json:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: executing shell script
        run: |
          if [ "${{ github.event.pull_request.title }}" !~ "^SRE-" ] && [ "${{ github.event.pull_request.title }}" !~ "^ZD-" ];
          then
            echo "PR title should start with [SRE-XXX] or [ZD-XXX]"
            exit 1
          fi
          if [ "${{ github.event.pull_request.head.ref }}" !~ "^SRE-" ] && [ "${{ github.event.pull_request.head.ref }}" !~ "^ZD-" ];
          then
            echo "Branch name should start with [SRE-XXX] or [ZD-XXX]"
            exit 1
      - name: Validate JSON
        uses: docker://orrosenblatt/validate-json-action:latest
        env:
          INPUT_SCHEMA: /schema.json
          INPUT_JSONS: /input.json

