name: validating json file
on: 
  pull_request:
    branches:
      - main
    paths:
      - 'input.json'
jobs:
  validate-json:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: executing shell script
        run: |
          whoami
          echo "validating json file"
      - name: Validate JSON
        uses: docker://orrosenblatt/validate-json-action:latest
        env:
          INPUT_SCHEMA: /schema.json
          INPUT_JSONS: /input.json

