name: validating json file
on: 
  pull_request:
    branches:
      - main
    paths:
      - 'input.json'
jobs:
  validate-json:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: executing shell script
        run: |
          echo ${{ github.event.pull_request.title }}
          echo ${{ github.event.pull_request.head.ref }}
          echo ${{ github.event.pull_request.head.sha }}
      - name: Validate JSON
        uses: docker://orrosenblatt/validate-json-action:latest
        env:
          INPUT_SCHEMA: /schema.json
          INPUT_JSONS: /input.json

